name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  CI:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            ruby: "3.0"
            task: spec
          - os: ubuntu-latest
            ruby: "truffleruby-head"
            task: spec
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Install Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby }}"
    - name: Install NodeJS 16.x
      uses: actions/setup-node@v3
      with:
        node-version: "16.x"
    - name: Install dependencies
      shell: bash
      run: "gem install --no-document bundler toys && bundle install"
    - name: Test ${{ matrix.task }}
      shell: bash
      run: toys do ${{ matrix.task }} < /dev/null
